### ISSUE TITLE
Use more descriptive page titles

### ISSUE THREAD

**Issue by aphedges** [usc-isi-i2/kgtk-search#22]
The KGTK search pages should have title text that shows the search term. Currently, all pages just have `Knowledge Graph Text Search`, which makes it hard to have multiple tabs open.

**Comment by g1eb** [comment]
Sounds like a good feature to add, I can take a first pass at adding this.

**Comment by g1eb** [comment]
I've added search term to the document title, it's on the `develop` branch too now.

**Comment by g1eb** [comment]
@saggu see if you like the `KG search: ${query}` or if the prefix should be something else, maybe `KGTK: {query}`?

**Comment by aphedges** [comment]
How about keeping the original wording but putting the query first, i.e., `${query} - Knowledge Graph Text Search`? A lot of sites do something similar. For example:

- [Python (programming language) - Wikipedia](https://en.wikipedia.org/wiki/Python_(programming_language))
- [foo - Google Search](https://www.google.com/search?q=foo)
- [After pushing AV1 codec, Google goes after Dolby with HDR and audio standards | Ars Technica](https://arstechnica.com/gadgets/2022/09/google-and-youtube-to-take-on-dolby-with-free-hdr-and-audio-standards/)

It doesn't really help if the distinguishing part gets cut off and all the tabs show `KG sear...`. In addition, the site has a unique favicon, so having the `KG search` first isn't necessary to distinguish from other sites.

**Comment by g1eb** [comment]
Good idea, it's on the `develop` branch for @saggu to test and redeploy on production

**Comment by saggu** [comment]
Deployed.

**Comment by aphedges** [comment]
I can confirm it works. Thank you!
