### ISSUE TITLE
Search results are not links

### ISSUE THREAD

**Issue by aphedges** [usc-isi-i2/kgtk-search#23]
The KGTK search doesn't treat KGTK browser pages as links, which makes them more annoying to work with. They should just be `<a target="_blank">` links (or similar) instead of relying on special JavaScript that forces a particular workflow.

**Comment by g1eb** [comment]
Alex are you referring to these links in the KGTK search results? 

<img width="949" alt="Screen Shot 2022-09-21 at 9 49 26 PM" src="https://user-images.githubusercontent.com/1916056/191661032-9be2654c-3fc4-4b85-9020-8aa1cfc43d78.png">


There was a reason for why they could not be as simple as a regular `<a />` tag. Of course, we can take a look at why that is and change the behaviour. 

> which makes them more annoying to work with

Could you elaborate on what makes these links more annoying to work with as opposed to regular `<a />` tags? Maybe there's a compromise to be made

**Comment by aphedges** [comment]
Yes, I am referring to these links.

> > which makes them more annoying to work with
> 
> Could you elaborate on what makes these links more annoying to work with as opposed to regular `<a />` tags? Maybe there's a compromise to be made

I want to do some things that are possible with ordinary links. For example, I'd like to be able to middle-click to open into a new background tab and right-click so I can copy the URL of the page. Currently, left- or middle-clicking it will open into a new foreground tab, which means I need to switch back and forth between tabs if I want to look at multiple results.

**Comment by g1eb** [comment]
Great, we have a fix that's in the `develop` branch now.

@saggu can help us test and deploy it when he get's a chance.

**Comment by saggu** [comment]
Deployed

**Comment by aphedges** [comment]
I can confirm it works. Thank you!
